### ISSUE TITLE
prep_enwik8.py is missing

### ISSUE THREAD

**Issue by ischlag** [Smerity/sha-rnn#13]
getdata.sh fails (not so obvious; missed it twice) 

reason:
prep_enwik8.py is missing

I copied pred_enwik8 from this other repository to process enwik8:
https://github.com/salesforce/awd-lstm-lm/blob/master/data/enwik8/prep_enwik8.py

Seems to work now and I'm trying to reproduce.

**Comment by stefan-it** [comment]
I think you just need to adjust the path to the `prep_enwik8.py` script.

It is located in the `data/enwik8` folder:

https://github.com/Smerity/sha-rnn/tree/master/data/enwik8
